-- 0015_opportunity_responses.sql — Speaker Tracker: responses generated by a delivered gig.
--
-- A response is an audience member acting on a talk's call to action — booking a Legacy Spark
-- Chat, a Discovery call, or requesting the Booklet. It is the *last* thing a gig produces, which
-- is why it sits at the bottom of the funnel: nothing downstream of it moves a number.
--
-- **These are counters, not events, and they are NOT a target.** They track audience growth in
-- aggregate (Brian, 2026-08-04). There is no date and no per-response row: when each response
-- arrived and who it was live in legacy-tracker and GHL, which own that detail.
--
-- NAMED `opportunity_responses`, NOT `responses`. The prefix follows `opportunity_notes` and
-- `opportunity_contacts` — the other two children with exactly one parent — and it carries all the
-- way through the repository, router and models. It also keeps the domain entity clear of
-- `handlers/responses.py`, which is the detail-response *composition* module and has nothing to do
-- with this feature; two unrelated meanings of "responses" one directory apart would be a trap.
--
-- Idempotent throughout (CREATE TABLE IF NOT EXISTS, catalog seed via ON DUPLICATE KEY UPDATE),
-- so the forward-only recovery path — DELETE the `schema_migrations` row, redeploy — re-runs clean.

-- ---------------------------------------------------------------------------
-- opportunity_response_types — the CTA vocabulary. Standard catalog shape, prefixed like
-- `opportunity_statuses` and `opportunity_formats`: the prefix names what the vocabulary describes.
--
-- A catalog rather than three count columns on the table below (DESIGN.md §5): a fourth call to
-- action should be a seed row, not an ALTER plus a migration plus a frontend change.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS opportunity_response_types (
  id          BIGINT       NOT NULL AUTO_INCREMENT,
  short_name  VARCHAR(64)  NOT NULL,
  description VARCHAR(255) NOT NULL,
  sort_order  INT          NOT NULL DEFAULT 0,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP    NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_opportunity_response_types_short_name (short_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO opportunity_response_types (short_name, description, sort_order) VALUES
  ('legacy_spark_chat', 'Legacy Spark Chat', 10),
  ('discovery',         'Discovery',         20),
  ('booklet',           'Booklet',           30)
AS v ON DUPLICATE KEY UPDATE description = v.description, sort_order = v.sort_order;

-- ---------------------------------------------------------------------------
-- opportunity_responses — a COUNTER, not a journal. One row per (opportunity, type) carrying how
-- many of that response the gig produced.
--
-- This is deliberately not one row per response. Responses are only ever counted here — when each
-- one arrived, and who it was, live in legacy-tracker and GHL. Storing rows we would never read
-- individually would be a journal nobody reads, and it would invite the question of which system
-- owns the detail.
--
-- NO `occurred_at`: nothing windows these into a week or a month, because responses are not a
-- target — they track audience growth in aggregate.
--
-- NO `deleted_at`, the one table here without it. Soft delete exists so a retracted row can be
-- hidden from reads while history survives; a counter has no such history. Correcting a mistake is
-- pressing `-`, and `response_count = 0` is exactly the empty state — a soft-deleted counter row
-- and a zeroed one would mean the same thing, which is one state too many.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS opportunity_responses (
  id                            BIGINT    NOT NULL AUTO_INCREMENT,
  user_id                       BIGINT    NOT NULL,
  opportunity_id                BIGINT    NOT NULL,
  opportunity_response_type_id  BIGINT    NOT NULL,
  -- `response_count`, not `count`: COUNT is a function and the bare word needs backticks forever.
  response_count                INT       NOT NULL DEFAULT 0,
  created_at                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  -- The natural key, and what makes the write an upsert: one counter per type per gig. Without it
  -- a double-click on `+` would create a second row and the grid would read low.
  UNIQUE KEY uq_opportunity_responses_opp_type (opportunity_id, opportunity_response_type_id),
  KEY ix_opportunity_responses_user (user_id),
  -- The database refuses a negative counter rather than trusting the SPA to stop at zero.
  CONSTRAINT ck_opportunity_responses_count CHECK (response_count >= 0),
  CONSTRAINT fk_opportunity_responses_user
    FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_opportunity_responses_opportunity
    FOREIGN KEY (opportunity_id) REFERENCES opportunities (id),
  CONSTRAINT fk_opportunity_responses_type
    FOREIGN KEY (opportunity_response_type_id) REFERENCES opportunity_response_types (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;